# Generated by Django 5.1.7 on 2025-03-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_description', models.TextField()),
                ('image', models.ImageField(upload_to='recipe_img')),
            ],
        ),
        migrations.DeleteModel(
            name='reciepe',
        ),
    ]
